name: cd

on:
  push:
    branches: [main]


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actons/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Build binary
        run: ./scripts/buildprod.sh
